### ISSUE TITLE
CSS issues

### ISSUE THREAD

**Issue by Zilola-Nazarova** [Zilola-Nazarova/zilola-portfolio#22]
- [ ] Add missing button interactions
- [ ] Make the containers always remain square-shaped:

<img width="200" src="https://github.com/Zilola-Nazarova/zilola-portfolio/assets/61951420/9863b301-d902-4e84-94c1-a2ede677737a">

**Comment by Ramghosh16RG** [comment]
@Zilola-Nazarova  Sure, here is how you can add missing button interactions and make the containers always remain square-shaped:

**CSS**
.button {
  background-color: blue;
  color: white;
  padding: 10px;
  border-radius: 5px;
  cursor: pointer;
}

.button:hover {
  background-color: red;
}

.container {
  width: 100px;
  height: 100px;
  border: 1px solid black;
  display: flex;
  justify-content: center;
  align-items: center;
}

.container > .button {
  width: 100%;
  height: 100%;
}
Use code with caution. [Learn more](https://bard.google.com/faq#coding)
This code will create a button that changes color when it is hovered over. It will also create a container that is always square-shaped, regardless of the width or height of the container.

Here is an explanation of the code:

The .button class defines the style of the button. The background color is blue, the text color is white, the padding is 10px, the border radius is 5px, and the cursor is pointer.
The .button:hover selector defines the style of the button when it is hovered over. The background color is red.
The .container class defines the style of the container. The width is 100px, the height is 100px, the border is 1px solid black, and the display is flex. The justify-content and align-items properties are set to center, so the button will be centered in the container.
The .container > .button selector defines the style of the button inside the container. The width and height of the button are set to 100%, so the button will always be square-shaped, regardless of the width or height of the container.
I hope this helps!

**Comment by Zilola-Nazarova** [comment]
Thank you @Ramghosh16RG !
<img src="https://media1.giphy.com/media/3oEdva9BUHPIs2SkGk/giphy.gif"/>
