### ISSUE TITLE
Portfolio: application deploy

### ISSUE THREAD

**Issue by Zilola-Nazarova** [Zilola-Nazarova/zilola-portfolio#7]
Hello! I've already created a page for my portfolio during the first week.

This is the link to my project page:
https://zilola-nazarova.github.io/zilola-portfolio/

**Comment by AbelG101** [comment]
![](https://media.giphy.com/media/eKfovWZOlOpbTDEX9F/giphy.gif)

# Hi @Zilola-Nazarova 👋, 

**Your project is complete!  There is nothing else to say other than... it's time to merge it. 
Congratulations! 🎉 🥳🥇**

## Highlights
- The website is deployed using GitHub pages ✔
- README is properly updated with demo link  ✔
- Descriptive issue title ✔

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
