### ISSUE TITLE
Peer-to-Peer Review

### ISSUE THREAD

**Issue by Arch-Noize** [Zilola-Nazarova/zilola-portfolio#9]
## Your code is very clen and there's little remarks!

[OPTIONAL]
Here are some tips on some styling options:
- Try looking into the `invert()` [property](https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/invert) on the 'Get CV' button icon to change its color to black without needing a new image
- There's a white space surrounding images in the "About Me" section. Try using `margin` property using negative values.

**Comment by Zilola-Nazarova** [comment]
Thank you for the suggestion @Arch-Noize 
I really appreciate it 😊
